#!/bin/sh
# Used by macros.cross-pkgconfig.
# PKG_CONFIG_SYSROOT_DIR prefixes -I/-L (needed: the compiler --sysroot
# does not rewrite absolute -I) and also every path-like --variable.
# Those --variable queries are almost always install destinations
# (tmpfilesdir, completionsdir, systemdsystemunitdir, dbus services).
# Unprefix them. Compile flags still go through --cflags/--libs.
var=0
flags=0
for a in "$@"; do
	case "$a" in
	--variable|--variable=*|-variable|--print-variables)
		var=1
		;;
	--cflags|--cflags-only-I|--cflags-only-other|--libs|--libs-only-L|--libs-only-other|--libs-only-l)
		flags=1
		;;
	esac
done
if [ "$var" -eq 1 ] && [ "$flags" -eq 0 ]; then
	unset PKG_CONFIG_SYSROOT_DIR
fi
exec /usr/bin/pkg-config "$@"
